### ISSUE TITLE
에러 발생 시 Slack으로 모니터링

### ISSUE THREAD

**Issue by jshjshjshjsh** [EnvEduPNU/EnvEdu_Server#95]

**Comment by 201724554** [comment]
## slack으로 에러 로그 전송 설정
* 발생한 문제
  * 로컬 환경에서 테스트 시에도 슬랙으로 에러 메세지를 보내지 않게 하기 위해 logback-spring.xml을 secret을 이용해 github action으로 작성
  * 이 경우, logback-spring.xml의 데이터 중 ""로 감싸진 문자열이나 ${}안의 데이터가 제대로 입력되지 않는 문제 발생
* 해결 방법
  * logback 파일을 secret으로 작성하지 않고 직접 github에 push 하는 것으로 변경
